management.endpoints.web.exposure.include: "*"
spring:
  jpa:
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    url: jdbc:h2:tcp://localhost/~/mem:testdb
    url: jdbc:mysql://localhost:3306/board_project
    username: lee
    password: outdoor_project1!
    driver-class-name: com.mysql.cj.jdbc.Driver
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1057834231340-gs8dnn7bgofkqjejverd4vfkujmrl8un.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot
