spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
#    driver-class-name: org.h2.Driver
    url: jdbc:mysql://localhost:3306/springboard
    username: leesunguk
    password: Naver920811!
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    url: jdbc:h2:tcp://localhost/~/mem:testdb
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1057834231340-gs8dnn7bgofkqjejverd4vfkujmrl8un.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot
